apiVersion: v1
kind: Service
metadata:
  name: carbide-hardware-health
  namespace: {{ include "carbide-hardware-health.namespace" . }}
  labels:
    {{- include "carbide-hardware-health.labels" . | nindent 4 }}
    app: carbide-hardware-health
    app.kubernetes.io/metrics: carbide-hardware-health
spec:
  selector:
    {{- include "carbide-hardware-health.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: metrics
      protocol: TCP
