apiVersion: v1
kind: Service
metadata:
  name: carbide-ssh-console-rs-metrics
  namespace: {{ include "carbide-ssh-console-rs.namespace" . }}
  labels:
    {{- include "carbide-ssh-console-rs.labels" . | nindent 4 }}
    app: carbide-ssh-console-rs
    app.kubernetes.io/metrics: carbide-ssh-console-rs
spec:
  selector:
    {{- include "carbide-ssh-console-rs.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.metrics.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
