apiVersion: v1
kind: Service
metadata:
  name: carbide-ssh-console-rs
  namespace: {{ include "carbide-ssh-console-rs.namespace" . }}
  labels:
    {{- include "carbide-ssh-console-rs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "carbide-ssh-console-rs.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: ssh
      protocol: TCP
