{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: carbide-pxe-external
  namespace: {{ include "carbide-pxe.namespace" . }}
  labels:
    {{- include "carbide-pxe.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: carbide-pxe
  annotations:
    metallb.universe.tf/allow-shared-ip: "carbide-pxe"
    {{- with .Values.externalService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.externalService.type | default "LoadBalancer" }}
  {{- if .Values.externalService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalService.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "carbide-pxe.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: carbide-pxe-external-80
  namespace: {{ include "carbide-pxe.namespace" . }}
  labels:
    {{- include "carbide-pxe.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: carbide-pxe
  annotations:
    metallb.universe.tf/allow-shared-ip: "carbide-pxe"
    {{- with .Values.externalService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.externalService.type | default "LoadBalancer" }}
  {{- if .Values.externalService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalService.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "carbide-pxe.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
{{- end }}
