apiVersion: v1
kind: Service
metadata:
  name: carbide-pxe-metrics
  namespace: {{ include "carbide-pxe.namespace" . }}
  labels:
    {{- include "carbide-pxe.labels" . | nindent 4 }}
    app: carbide-pxe
    app.kubernetes.io/metrics: carbide-pxe
spec:
  selector:
    {{- include "carbide-pxe.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.port }}
