apiVersion: v2
name: carbide-dsx-exchange-consumer
description: Helm chart for the Carbide DSX Exchange Consumer component
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - carbide
  - dsx-exchange-consumer
  - forge
