{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: carbide-api-external
  namespace: {{ include "carbide-api.namespace" . }}
  labels:
    {{- include "carbide-api.labels" . | nindent 4 }}
  {{- with .Values.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.type | default "LoadBalancer" }}
  {{- if .Values.externalService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalService.externalTrafficPolicy }}
  {{- end }}
  internalTrafficPolicy: Local
  selector:
    {{- include "carbide-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      targetPort: {{ .Values.service.grpc.port }}
      name: grpc
      protocol: TCP
{{- end }}
