kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-api
  namespace: {{ include "carbide-api.namespace" . }}
  labels:
    {{- include "carbide-api.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-api
  namespace: {{ include "carbide-api.namespace" . }}
  labels:
    {{- include "carbide-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-api
subjects:
  - kind: ServiceAccount
    name: carbide-api
    namespace: {{ include "carbide-api.namespace" . }}
