## What address to listen on.
listen_address = "[::]:22"
metrics_address = "[::]:9009"

## Address for carbide-api
carbide_url = "https://carbide-api.forge-system.svc.cluster.local:1079"

## Path to root CA cert for carbide-api
forge_root_ca_path = "/var/run/secrets/spiffe.io/ca.crt"

## Client cert path to communicate with carbide-api
client_cert_path = "/var/run/secrets/spiffe.io/tls.crt"

## Client key path to communicate with carbide-api
client_key_path = "/var/run/secrets/spiffe.io/tls.key"

## Path to the SSH host key.
host_key = "/etc/ssh/ssh_host_ed25519_key"

## Allow SSH'ing to DPU consoles
dpus = true

## Disable client SSH auth enforcement. This must NEVER be set in production: It forces all incoming
## client connections to succeed.
insecure = false

## Signing CA fingerprints for openssh certificates. Add your CA fingerprints here.
openssh_certificate_ca_fingerprints = []

## Roles which determine admin access (logins with an openssh certificate, signed by the above
## fingerprints, containing this role in its Key ID, are considered admins and can log into machines
## directly.)
admin_certificate_role = ""

## If true, use insecure ciphers when connecting to IPMI, like SHA1. Useful for ipmi_sim.
insecure_ipmi_ciphers = false

## Optional: For development mode, gives keys that are authorized to connect to ssh-console. Meant
## for integration tests. For interactive use, consider using openssh certificates instead.
# authorized_keys_path = <path>

## How often to poll the carbide API server for what machines are available
api_poll_interval = "180s"

## Whether to output the console data for each machine to a log file
console_logging_enabled = true

## Where to write console logs for each machine, if enabled
console_logs_path = "/var/log/consoles"
