apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envFrom.carbideDnsConfig.configMapName }}
  namespace: {{ include "carbide-dns.namespace" . }}
  labels:
    {{- include "carbide-dns.labels" . | nindent 4 }}
data:
  CARBIDE_API: {{ printf "carbide-api.%s.svc.cluster.local:%s" (include "carbide-dns.namespace" .) (.Values.config.carbideApiPort | default "1079") | quote }}
  CARBIDE_API_HOST: {{ printf "carbide-api.%s.svc.cluster.local" (include "carbide-dns.namespace" .) | quote }}
  CARBIDE_API_PORT: {{ .Values.config.carbideApiPort | default "1079" | quote }}
  {{- range $key, $value := .Values.config.extraData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
