apiVersion: v1
kind: Service
metadata:
  name: carbide-dns
  namespace: {{ include "carbide-dns.namespace" . }}
  labels:
    {{- include "carbide-dns.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "carbide-dns.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      protocol: {{ .protocol }}
    {{- end }}
