{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forge-unbound-metrics
  namespace: {{ include "unbound.namespace" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
    app: forge-unbound
  annotations:
    {{- include "unbound.annotations" . | nindent 4 }}
spec:
  endpoints:
    - port: unbound-metrics
      scheme: http
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: forge-unbound
  namespaceSelector:
    any: true
{{- end }}
