apiVersion: v1
kind: Service
metadata:
  name: forge-unbound
  namespace: {{ include "unbound.namespace" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
  annotations:
    {{- include "unbound.annotations" . | nindent 4 }}
spec:
  selector:
    {{- include "unbound.selectorLabels" . | nindent 4 }}
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 9167
      protocol: TCP
      targetPort: metrics
      name: unbound-metrics
