apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carbide-dhcp-certificate
  namespace: {{ include "carbide-dhcp.namespace" . }}
  labels:
    {{- include "carbide-dhcp.labels" . | nindent 4 }}
spec:
  {{- include "carbide-dhcp.certificateSpec" (dict "name" "carbide-dhcp-certificate" "cert" .Values.certificate "global" .Values.global "namespace" (include "carbide-dhcp.namespace" .)) | nindent 2 }}
