apiVersion: v1
kind: Service
metadata:
  name: carbide-dhcp-metrics
  namespace: {{ include "carbide-dhcp.namespace" . }}
  labels:
    {{- include "carbide-dhcp.labels" . | nindent 4 }}
    app: carbide-dhcp
    app.kubernetes.io/metrics: carbide-dhcp
spec:
  selector:
    {{- include "carbide-dhcp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.metrics.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
