apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbide-dsx-exchange-consumer
  namespace: {{ include "carbide-dsx-exchange-consumer.namespace" . }}
  labels:
    {{- include "carbide-dsx-exchange-consumer.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-dsx-exchange-consumer
  namespace: {{ include "carbide-dsx-exchange-consumer.namespace" . }}
  labels:
    {{- include "carbide-dsx-exchange-consumer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-dsx-exchange-consumer
  namespace: {{ include "carbide-dsx-exchange-consumer.namespace" . }}
  labels:
    {{- include "carbide-dsx-exchange-consumer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-dsx-exchange-consumer
subjects:
  - kind: ServiceAccount
    name: carbide-dsx-exchange-consumer
    namespace: {{ include "carbide-dsx-exchange-consumer.namespace" . }}
