{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: carbide-dsx-exchange-consumer-metrics
  namespace: {{ include "carbide-dsx-exchange-consumer.namespace" . }}
  labels:
    {{- include "carbide-dsx-exchange-consumer.labels" . | nindent 4 }}
    app: carbide-dsx-exchange-consumer
    prometheus: forge-monitoring
spec:
  {{- include "carbide-dsx-exchange-consumer.serviceMonitorSpec" (dict "name" "carbide-dsx-exchange-consumer" "port" "metrics" "monitor" .Values.serviceMonitor "namespace" (include "carbide-dsx-exchange-consumer.namespace" .)) | nindent 2 }}
{{- end }}
