apiVersion: v1
kind: Service
metadata:
  name: carbide-dsx-exchange-consumer
  namespace: {{ include "carbide-dsx-exchange-consumer.namespace" . }}
  labels:
    {{- include "carbide-dsx-exchange-consumer.labels" . | nindent 4 }}
    app: carbide-dsx-exchange-consumer
    app.kubernetes.io/metrics: carbide-dsx-exchange-consumer
spec:
  selector:
    {{- include "carbide-dsx-exchange-consumer.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: metrics
      protocol: TCP
